# Generated by Django 4.1.7 on 2023-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0002_board_num_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='front',
            field=models.IntegerField(default=0),
        ),
    ]
