# Generated by Django 4.1.7 on 2023-02-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0004_alter_player_survive'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=97),
        ),
    ]
