# Generated by Django 4.1.7 on 2023-02-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0005_board_code_alter_board_id_alter_ship_atk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='front',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=33),
        ),
    ]
