# Generated by Django 4.1.7 on 2023-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0006_alter_player_front_alter_ship_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=29),
        ),
    ]
