# Generated by Django 4.1.7 on 2023-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0007_board_turn_alter_ship_atk_alter_ship_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='temp_status',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=61),
        ),
    ]
