# Generated by Django 4.1.7 on 2023-02-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0010_alter_ship_atk_alter_ship_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='ship',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HttpMethods.board'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HttpMethods.player'),
        ),
    ]
