# Generated by Django 4.1.7 on 2023-02-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0012_alter_ship_atk_alter_ship_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=35),
        ),
    ]
