# Generated by Django 4.1.7 on 2023-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0014_remove_board_temp_status_alter_ship_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=29),
        ),
    ]
