# Generated by Django 4.1.7 on 2023-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0015_board_status_board_winner_alter_ship_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='survive',
        ),
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=44),
        ),
    ]
