# Generated by Django 4.1.7 on 2023-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0016_remove_player_survive_alter_ship_atk_alter_ship_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='survive',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(default=24),
        ),
    ]
