# Generated by Django 4.1.7 on 2023-02-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HttpMethods', '0018_alter_ship_atk_alter_ship_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Atk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Hp',
            field=models.IntegerField(),
        ),
    ]
